package de.pixelprotect.model;

public enum ActionType {
    BREAK, PLACE, BURN, EXPLOSION, PISTON, FLUID, GROW, FORM, SPREAD, ENTITY_CHANGE,
    BUCKET, CONTAINER, INVENTORY, ITEM_DROP, ITEM_PICKUP, ITEM_DESPAWN, ENTITY_SPAWN, ENTITY_DEATH,
    ENTITY_REMOVE, ENTITY_DAMAGE, PROJECTILE, INTERACT, ENTITY_INTERACT, SIGN, CHAT,
    COMMAND, SESSION, CRAFT, TRADE, WORLD_EDIT,
    DECAY, MOISTURE, SCULK, CAULDRON, DISPENSE, COMPOST, SHEAR, TNT_PRIME, BLOCK_BREAK,
    VAULT, PORTAL, STRUCTURE, BOOKSHELF, FLOWER_POT, CAMPFIRE, LECTERN
}
