package de.pixelprotect.storage;

import com.google.gson.Gson;
import de.pixelprotect.model.ActionType;
import de.pixelprotect.model.AuditEntry;
import de.pixelprotect.model.AuditQuery;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardOpenOption;
import java.sql.*;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import java.util.concurrent.ArrayBlockingQueue;
import java.util.concurrent.BlockingQueue;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;
import java.util.logging.Logger;

/** Durable single-writer SQLite audit storage. */
public class Database implements AutoCloseable {
    protected static final int SCHEMA_VERSION=7;protected static final Gson GSON=new Gson();
    protected final Path file,overflowFile;protected final Logger logger;protected final int batchSize;protected final long flushIntervalMillis;protected final BlockingQueue<AuditEntry> queue;
    protected final ScheduledExecutorService executor=Executors.newSingleThreadScheduledExecutor(r->{Thread t=new Thread(r,"PixelProtect-Database");t.setDaemon(true);return t;});
    protected Connection connection;protected volatile boolean running;
    public Database(Path file,int queueCapacity,int batchSize,long flushIntervalMillis,Logger logger){this.file=file;this.overflowFile=file.resolveSibling(file.getFileName()+".overflow.jsonl");this.logger=logger;this.queue=new ArrayBlockingQueue<>(Math.max(1,queueCapacity));this.batchSize=Math.max(1,batchSize);this.flushIntervalMillis=Math.max(25L,flushIntervalMillis);}
    public void open()throws SQLException,IOException{Path p=file.toAbsolutePath().getParent();if(p!=null)Files.createDirectories(p);connection=DriverManager.getConnection("jdbc:sqlite:"+file.toAbsolutePath());try(Statement s=connection.createStatement()){s.execute("PRAGMA journal_mode=WAL");s.execute("PRAGMA synchronous=NORMAL");s.execute("PRAGMA foreign_keys=ON");s.execute("PRAGMA busy_timeout=5000");migrate(s);}running=true;replayOverflow();executor.scheduleAtFixedRate(this::flushQueue,flushIntervalMillis,flushIntervalMillis,TimeUnit.MILLISECONDS);}
    protected void migrate(Statement s)throws SQLException{ s.executeUpdate("CREATE TABLE IF NOT EXISTS pixelprotect_meta (key TEXT PRIMARY KEY,value TEXT NOT NULL)");int v=0;try(ResultSet r=s.executeQuery("SELECT value FROM pixelprotect_meta WHERE key='schema_version'")){if(r.next())v=Integer.parseInt(r.getString(1));}
        if(v<1){s.executeUpdate("CREATE TABLE IF NOT EXISTS audit (id INTEGER PRIMARY KEY AUTOINCREMENT,time INTEGER NOT NULL,world TEXT NOT NULL,x INTEGER NOT NULL,y INTEGER NOT NULL,z INTEGER NOT NULL,actor_uuid TEXT,actor_name TEXT NOT NULL,action TEXT NOT NULL,before_data TEXT NOT NULL,after_data TEXT NOT NULL,before_inventory BLOB,after_inventory BLOB)");s.executeUpdate("CREATE INDEX IF NOT EXISTS idx_audit_location_time ON audit(world,x,z,time DESC)");s.executeUpdate("CREATE INDEX IF NOT EXISTS idx_audit_actor_time ON audit(actor_uuid,time DESC)");s.executeUpdate("CREATE INDEX IF NOT EXISTS idx_audit_action_time ON audit(action,time DESC)");s.executeUpdate("CREATE INDEX IF NOT EXISTS idx_audit_time ON audit(time)");v=1;}
        if(v<2){s.executeUpdate("CREATE INDEX IF NOT EXISTS idx_audit_world_y_time ON audit(world,y,time DESC)");s.executeUpdate("CREATE INDEX IF NOT EXISTS idx_audit_world_action_time ON audit(world,action,time DESC)");v=2;}
        if(v<3){s.executeUpdate("CREATE TABLE IF NOT EXISTS rollback_jobs (id TEXT PRIMARY KEY,status TEXT NOT NULL,total INTEGER NOT NULL,processed INTEGER NOT NULL DEFAULT 0,applied INTEGER NOT NULL DEFAULT 0,skipped INTEGER NOT NULL DEFAULT 0,error TEXT,created_at INTEGER NOT NULL,finished_at INTEGER)");s.executeUpdate("CREATE TABLE IF NOT EXISTS rollback_job_entries (job_id TEXT NOT NULL,audit_id BIGINT NOT NULL,applied INTEGER NOT NULL DEFAULT 0,PRIMARY KEY(job_id,audit_id),FOREIGN KEY(job_id) REFERENCES rollback_jobs(id) ON DELETE CASCADE,FOREIGN KEY(audit_id) REFERENCES audit(id) ON DELETE CASCADE)");s.executeUpdate("CREATE INDEX IF NOT EXISTS idx_rollback_job_entries_applied ON rollback_job_entries(job_id,applied)");v=3;}
        if(v<4){s.executeUpdate("CREATE TABLE IF NOT EXISTS rollback_restores (id TEXT PRIMARY KEY,source_job_id TEXT NOT NULL,status TEXT NOT NULL,applied INTEGER NOT NULL DEFAULT 0,skipped INTEGER NOT NULL DEFAULT 0,error TEXT,created_at BIGINT NOT NULL,finished_at BIGINT,FOREIGN KEY(source_job_id) REFERENCES rollback_jobs(id) ON DELETE CASCADE)");s.executeUpdate("CREATE INDEX IF NOT EXISTS idx_rollback_restores_source ON rollback_restores(source_job_id,created_at DESC)");v=4;}
        if(v<5){addColumnIfMissing(s,"audit","before_block_entity","TEXT");addColumnIfMissing(s,"audit","after_block_entity","TEXT");v=5;}
        if(v<6){addColumnIfMissing(s,"audit","transaction_id","VARCHAR(36)");addColumnIfMissing(s,"audit","sequence","BIGINT NOT NULL DEFAULT 0");s.executeUpdate("CREATE INDEX IF NOT EXISTS idx_audit_transaction ON audit(transaction_id,sequence,id)");v=6;}
        if(v<7){s.executeUpdate("CREATE TABLE IF NOT EXISTS entity_audit (id BIGINT AUTO_INCREMENT PRIMARY KEY,audit_id BIGINT NOT NULL,world VARCHAR(36) NOT NULL,x DOUBLE NOT NULL,y DOUBLE NOT NULL,z DOUBLE NOT NULL,actor_uuid VARCHAR(36),action VARCHAR(64) NOT NULL,before_snapshot LONGTEXT,after_snapshot LONGTEXT,spawn_reason VARCHAR(64),remove_cause VARCHAR(64),transaction_id VARCHAR(36),sequence BIGINT NOT NULL DEFAULT 0,FOREIGN KEY(audit_id) REFERENCES audit(id) ON DELETE CASCADE)");s.executeUpdate("CREATE INDEX IF NOT EXISTS idx_entity_audit_location_time ON entity_audit(world,x,y,z,audit_id)");s.executeUpdate("CREATE TABLE IF NOT EXISTS inventory_audit (id BIGINT AUTO_INCREMENT PRIMARY KEY,audit_id BIGINT NOT NULL,world VARCHAR(36) NOT NULL,x INT NOT NULL,y INT NOT NULL,z INT NOT NULL,actor_uuid VARCHAR(36),slot_diff LONGTEXT NOT NULL,transaction_id VARCHAR(36),sequence BIGINT NOT NULL DEFAULT 0,FOREIGN KEY(audit_id) REFERENCES audit(id) ON DELETE CASCADE)");s.executeUpdate("CREATE INDEX IF NOT EXISTS idx_inventory_audit_location ON inventory_audit(world,x,y,z,audit_id)");v=7;}
        if(v!=SCHEMA_VERSION)throw new SQLException("Unsupported PixelProtect schema version: "+v);s.executeUpdate("UPDATE rollback_jobs SET status='FAILED',error='Server restarted while rollback was running.',finished_at="+System.currentTimeMillis()+" WHERE status='RUNNING'");try(PreparedStatement u=connection.prepareStatement("INSERT INTO pixelprotect_meta(key,value) VALUES(?,?) ON DUPLICATE KEY UPDATE value=VALUES(value)")){u.setString(1,"schema_version");u.setString(2,Integer.toString(v));u.executeUpdate();}}
    protected static void addColumnIfMissing(Statement s,String t,String c,String type)throws SQLException{try{s.executeUpdate("ALTER TABLE "+t+" ADD COLUMN "+c+" "+type);}catch(SQLException e){if(!e.getMessage().toLowerCase().contains("duplicate"))throw e;}}
    public boolean record(AuditEntry e){if(!running)return false;if(queue.offer(e))return true;return spool(e);}protected boolean spool(AuditEntry e){try{Files.writeString(overflowFile,GSON.toJson(e)+System.lineSeparator(),StandardCharsets.UTF_8,StandardOpenOption.CREATE,StandardOpenOption.WRITE,StandardOpenOption.APPEND);return true;}catch(IOException x){logger.log(java.util.logging.Level.SEVERE,"Failed to spool audit record.",x);return false;}}
    public CompletableFuture<List<AuditEntry>> query(AuditQuery q){return executeAsync(()->{flushQueue();return queryBlocking(q);});}public CompletableFuture<Long> count(AuditQuery q){return executeAsync(()->{flushQueue();return countBlocking(q);});}public CompletableFuture<List<AuditEntry>> query(UUID world,int x,int y,int z,int radius,long since,long until,String actor,int limit){return query(new AuditQuery(world,x,y,z,radius,since,until,actor,java.util.Set.of(),java.util.Set.of(),java.util.Set.of(),java.util.Set.of(),limit));}
    protected List<AuditEntry> queryBlocking(AuditQuery q)throws SQLException{QuerySql b=buildQuery(q,false);List<Object>p=new ArrayList<>(b.params());p.add(q.limit());p.add(q.offset());try(PreparedStatement s=connection.prepareStatement(b.sql()+" ORDER BY time DESC,id DESC LIMIT ? OFFSET ?")){bind(s,p);try(ResultSet r=s.executeQuery()){List<AuditEntry>o=new ArrayList<>();while(r.next())o.add(read(r));return o;}}}
    protected long countBlocking(AuditQuery q)throws SQLException{QuerySql b=buildQuery(q,true);try(PreparedStatement s=connection.prepareStatement(b.sql())){bind(s,b.params());try(ResultSet r=s.executeQuery()){return r.next()?r.getLong(1):0L;}}}
    protected QuerySql buildQuery(AuditQuery q,boolean count){int r=q.radius();long rs=(long)r*r;StringBuilder s=new StringBuilder(count?"SELECT COUNT(*) FROM audit WHERE ":"SELECT id,time,world,x,y,z,actor_uuid,actor_name,action,before_data,after_data,before_inventory,after_inventory,before_block_entity,after_block_entity,transaction_id,sequence FROM audit WHERE ");s.append("world=? AND x BETWEEN ? AND ? AND y BETWEEN ? AND ? AND z BETWEEN ? AND ? AND ((x-?)*(x-?)+(y-?)*(y-?)+(z-?)*(z-?))<=? AND time>=? AND time<=?");List<Object>p=new ArrayList<>();p.add(q.world().toString());p.add(q.centerX()-r);p.add(q.centerX()+r);p.add(q.centerY()-r);p.add(q.centerY()+r);p.add(q.centerZ()-r);p.add(q.centerZ()+r);p.add(q.centerX());p.add(q.centerX());p.add(q.centerY());p.add(q.centerY());p.add(q.centerZ());p.add(q.centerZ());p.add(rs);p.add(q.since());p.add(q.until());if(q.actorName()!=null&&!q.actorName().isBlank()){s.append(" AND actor_name=?");p.add(q.actorName());}appendActions(s,p,q.includeActions(),true);appendActions(s,p,q.excludeActions(),false);appendBlocks(s,p,q.includeBlocks(),false);appendBlocks(s,p,q.excludeBlocks(),true);return new QuerySql(s.toString(),p);}
    protected static void appendActions(StringBuilder s,List<Object>p,java.util.Set<ActionType>a,boolean inc){if(a.isEmpty())return;s.append(inc?" AND action IN (":" AND action NOT IN (");s.append("?,".repeat(a.size()));s.setLength(s.length()-1);s.append(')');a.forEach(x->p.add(x.name()));}protected static void appendBlocks(StringBuilder s,List<Object>p,java.util.Set<String>b,boolean ex){for(String x:b){s.append(ex?" AND before_data NOT LIKE ? AND after_data NOT LIKE ?":" AND (before_data LIKE ? OR after_data LIKE ?)");p.add(x+"%");p.add(x+"%");}}protected static void bind(PreparedStatement s,List<Object>p)throws SQLException{for(int i=0;i<p.size();i++){Object v=p.get(i);if(v instanceof Integer n)s.setInt(i+1,n);else if(v instanceof Long n)s.setLong(i+1,n);else s.setString(i+1,v.toString());}}
    public CompletableFuture<Integer> purgeBefore(long cutoff){return executeAsync(()->{flushQueue();try(PreparedStatement s=connection.prepareStatement("DELETE FROM audit WHERE time < ?")){s.setLong(1,cutoff);return s.executeUpdate();}});}public CompletableFuture<Long> count(){return executeAsync(()->{try(var s=connection.createStatement();var r=s.executeQuery("SELECT COUNT(*) FROM audit")){return r.next()?r.getLong(1):0L;}});}public CompletableFuture<Long> failedRollbackCount(){return executeAsync(()->{try(var s=connection.createStatement();var r=s.executeQuery("SELECT COUNT(*) FROM rollback_jobs WHERE status='FAILED'")){return r.next()?r.getLong(1):0L;}});}
    public CompletableFuture<Void> recordEntityAudit(EntityAuditRecord r){return executeAsync(()->{try(PreparedStatement s=connection.prepareStatement("INSERT INTO entity_audit(audit_id,world,x,y,z,actor_uuid,action,before_snapshot,after_snapshot,spawn_reason,remove_cause,transaction_id,sequence) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)")){s.setLong(1,r.auditId());s.setString(2,r.world().toString());s.setDouble(3,r.x());s.setDouble(4,r.y());s.setDouble(5,r.z());if(r.actor()==null)s.setNull(6,Types.VARCHAR);else s.setString(6,r.actor().toString());s.setString(7,r.action().name());s.setString(8,r.beforeSnapshot());s.setString(9,r.afterSnapshot());s.setString(10,r.spawnReason());s.setString(11,r.removeCause());s.setString(12,r.transactionId()==null?null:r.transactionId().toString());s.setLong(13,r.sequence());s.executeUpdate();}return null;});}
    public CompletableFuture<Void> recordInventoryAudit(InventoryAuditRecord r){return executeAsync(()->{try(PreparedStatement s=connection.prepareStatement("INSERT INTO inventory_audit(audit_id,world,x,y,z,actor_uuid,slot_diff,transaction_id,sequence) VALUES(?,?,?,?,?,?,?,?,?)")){s.setLong(1,r.auditId());s.setString(2,r.world().toString());s.setInt(3,r.x());s.setInt(4,r.y());s.setInt(5,r.z());if(r.actor()==null)s.setNull(6,Types.VARCHAR);else s.setString(6,r.actor().toString());s.setString(7,r.slotDiff());s.setString(8,r.transactionId()==null?null:r.transactionId().toString());s.setLong(9,r.sequence());s.executeUpdate();}return null;});}
    public CompletableFuture<Void> createRollbackJob(UUID id,List<AuditEntry>e){List<AuditEntry>x=List.copyOf(e);return executeAsync(()->{flushQueue();connection.setAutoCommit(false);try(PreparedStatement j=connection.prepareStatement("INSERT INTO rollback_jobs(id,status,total,created_at) VALUES(?,?,?,?)");PreparedStatement q=connection.prepareStatement("INSERT INTO rollback_job_entries(job_id,audit_id) VALUES(?,?)")){j.setString(1,id.toString());j.setString(2,"RUNNING");j.setInt(3,x.size());j.setLong(4,System.currentTimeMillis());j.executeUpdate();for(AuditEntry a:x){q.setString(1,id.toString());q.setLong(2,a.id());q.addBatch();}q.executeBatch();connection.commit();}catch(SQLException ex){connection.rollback();throw ex;}finally{connection.setAutoCommit(true);}return null;});}
    public CompletableFuture<Void> updateRollbackJob(UUID id,String status,int processed,int applied,int skipped,String error){return executeAsync(()->{try(PreparedStatement s=connection.prepareStatement("UPDATE rollback_jobs SET status=?,processed=?,applied=?,skipped=?,error=?,finished_at=? WHERE id=?")){s.setString(1,status);s.setInt(2,processed);s.setInt(3,applied);s.setInt(4,skipped);if(error==null)s.setNull(5,Types.VARCHAR);else s.setString(5,error);if("RUNNING".equals(status))s.setNull(6,Types.BIGINT);else s.setLong(6,System.currentTimeMillis());s.setString(7,id.toString());s.executeUpdate();}return null;});}
    public CompletableFuture<Void> markRollbackApplied(UUID id,List<Long>ids){return executeAsync(()->{try(PreparedStatement s=connection.prepareStatement("UPDATE rollback_job_entries SET applied=1 WHERE job_id=? AND audit_id=?")){for(long n:ids){s.setString(1,id.toString());s.setLong(2,n);s.addBatch();}s.executeBatch();}return null;});}
    public CompletableFuture<RollbackJobRecord> rollbackJob(UUID id){return executeAsync(()->{try(PreparedStatement s=connection.prepareStatement("SELECT id,status,total,processed,applied,skipped,error,created_at,finished_at FROM rollback_jobs WHERE id=?")){s.setString(1,id.toString());try(ResultSet r=s.executeQuery()){if(!r.next())return null;return new RollbackJobRecord(UUID.fromString(r.getString(1)),r.getString(2),r.getInt(3),r.getInt(4),r.getInt(5),r.getInt(6),r.getString(7),r.getLong(8),r.getLong(9));}}});}
    public CompletableFuture<List<AuditEntry>> appliedRollbackEntries(UUID id){return executeAsync(()->{flushQueue();List<AuditEntry>e=new ArrayList<>();try(PreparedStatement s=connection.prepareStatement("SELECT a.id,a.time,a.world,a.x,a.y,a.z,a.actor_uuid,a.actor_name,a.action,a.before_data,a.after_data,a.before_inventory,a.after_inventory,a.before_block_entity,a.after_block_entity,a.transaction_id,a.sequence FROM rollback_job_entries j JOIN audit a ON a.id=j.audit_id WHERE j.job_id=? AND j.applied=1 ORDER BY a.id ASC")){s.setString(1,id.toString());try(ResultSet r=s.executeQuery()){while(r.next())e.add(read(r));}}return e;});}
    public CompletableFuture<UUID> createRestore(UUID source){UUID id=UUID.randomUUID();return executeAsync(()->{try(PreparedStatement s=connection.prepareStatement("INSERT INTO rollback_restores(id,source_job_id,status,created_at) VALUES(?,?,?,?)")){s.setString(1,id.toString());s.setString(2,source.toString());s.setString(3,"RUNNING");s.setLong(4,System.currentTimeMillis());s.executeUpdate();}return id;});}
    public CompletableFuture<Void> updateRestore(UUID id,String status,int applied,int skipped,String error){return executeAsync(()->{try(PreparedStatement s=connection.prepareStatement("UPDATE rollback_restores SET status=?,applied=?,skipped=?,error=?,finished_at=? WHERE id=?")){s.setString(1,status);s.setInt(2,applied);s.setInt(3,skipped);if(error==null)s.setNull(4,Types.VARCHAR);else s.setString(4,error);if("RUNNING".equals(status))s.setNull(5,Types.BIGINT);else s.setLong(5,System.currentTimeMillis());s.setString(6,id.toString());s.executeUpdate();}return null;});}
    protected void flushQueue(){if(queue.isEmpty()||connection==null)return;List<AuditEntry>b=new ArrayList<>(batchSize);queue.drainTo(b,batchSize);try{insertBatch(b);}catch(SQLException ex){for(AuditEntry e:b)spool(e);}replayOverflow();}
    protected void replayOverflow(){if(!Files.exists(overflowFile)||connection==null)return;Path replay=overflowFile.resolveSibling(overflowFile.getFileName()+".replay");try{Files.move(overflowFile,replay,java.nio.file.StandardCopyOption.REPLACE_EXISTING);List<String>lines=Files.readAllLines(replay,StandardCharsets.UTF_8);List<AuditEntry>e=new ArrayList<>();int consumed=0;for(String line:lines){if(line.isBlank()){consumed++;continue;}try{e.add(GSON.fromJson(line,AuditEntry.class));consumed++;if(e.size()>=batchSize)break;}catch(RuntimeException x){consumed++;}}if(!e.isEmpty())insertBatch(e);List<String>remaining=lines.subList(consumed,lines.size());if(!remaining.isEmpty())Files.write(overflowFile,remaining,StandardCharsets.UTF_8,StandardOpenOption.CREATE,StandardOpenOption.TRUNCATE_EXISTING);Files.deleteIfExists(replay);}catch(Exception x){try{if(Files.exists(replay))Files.move(replay,overflowFile,java.nio.file.StandardCopyOption.REPLACE_EXISTING);}catch(IOException ignored){}}}
    protected void insertBatch(List<AuditEntry>e)throws SQLException{if(e.isEmpty())return;connection.setAutoCommit(false);try(PreparedStatement s=connection.prepareStatement("INSERT INTO audit(time,world,x,y,z,actor_uuid,actor_name,action,before_data,after_data,before_inventory,after_inventory,before_block_entity,after_block_entity,transaction_id,sequence) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)")){for(AuditEntry a:e){int i=1;s.setLong(i++,a.time());s.setString(i++,a.world().toString());s.setInt(i++,a.x());s.setInt(i++,a.y());s.setInt(i++,a.z());if(a.actor()==null)s.setNull(i++,Types.VARCHAR);else s.setString(i++,a.actor().toString());s.setString(i++,a.actorName());s.setString(i++,a.action().name());s.setString(i++,a.beforeData());s.setString(i++,a.afterData());s.setBytes(i++,a.beforeInventory());s.setBytes(i++,a.afterInventory());s.setString(i++,a.beforeBlockEntity());s.setString(i++,a.afterBlockEntity());if(a.transactionId()==null)s.setNull(i++,Types.VARCHAR);else s.setString(i++,a.transactionId().toString());s.setLong(i,a.sequence());s.addBatch();}s.executeBatch();connection.commit();}catch(SQLException ex){connection.rollback();throw ex;}finally{connection.setAutoCommit(true);}}
    protected AuditEntry read(ResultSet r)throws SQLException{String a=r.getString("actor_uuid"),t=r.getString("transaction_id");return new AuditEntry(r.getLong("id"),r.getLong("time"),UUID.fromString(r.getString("world")),r.getInt("x"),r.getInt("y"),r.getInt("z"),a==null?null:UUID.fromString(a),r.getString("actor_name"),ActionType.valueOf(r.getString("action")),r.getString("before_data"),r.getString("after_data"),r.getBytes("before_inventory"),r.getBytes("after_inventory"),r.getString("before_block_entity"),r.getString("after_block_entity"),t==null?null:UUID.fromString(t),r.getLong("sequence"));}
    protected <T>CompletableFuture<T>executeAsync(SqlSupplier<T>s){CompletableFuture<T>f=new CompletableFuture<>();executor.execute(()->{try{f.complete(s.get());}catch(Throwable t){f.completeExceptionally(t);}});return f;}
    public int queueSize(){return queue.size();}public int schemaVersion(){return SCHEMA_VERSION;}
    @Override public void close(){running=false;executor.shutdown();try{executor.awaitTermination(10,TimeUnit.SECONDS);}catch(InterruptedException e){Thread.currentThread().interrupt();}if(connection!=null)try{flushQueue();connection.close();}catch(SQLException e){logger.log(java.util.logging.Level.SEVERE,"Database close failed.",e);}}
    protected record QuerySql(String sql,List<Object>params){}@FunctionalInterface protected interface SqlSupplier<T>{T get()throws Exception;}
    public record RollbackJobRecord(UUID id,String status,int total,int processed,int applied,int skipped,String error,long createdAt,long finishedAt){}
    public record EntityAuditRecord(long auditId,UUID world,double x,double y,double z,UUID actor,ActionType action,String beforeSnapshot,String afterSnapshot,String spawnReason,String removeCause,UUID transactionId,long sequence){}
    public record InventoryAuditRecord(long auditId,UUID world,int x,int y,int z,UUID actor,String slotDiff,UUID transactionId,long sequence){}
}
