package de.pixelprotect.command;

import com.mojang.brigadier.Command;
import com.mojang.brigadier.arguments.IntegerArgumentType;
import com.mojang.brigadier.arguments.StringArgumentType;
import com.mojang.brigadier.builder.LiteralArgumentBuilder;
import de.pixelprotect.model.AuditEntry;
import de.pixelprotect.model.AuditQuery;
import de.pixelprotect.service.InspectService;
import de.pixelprotect.service.RollbackService;
import de.pixelprotect.storage.Database;
import io.papermc.paper.command.brigadier.CommandSourceStack;
import io.papermc.paper.command.brigadier.Commands;
import org.bukkit.Bukkit;
import org.bukkit.Location;
import org.bukkit.World;
import org.bukkit.command.CommandSender;
import org.bukkit.entity.Player;
import org.bukkit.plugin.Plugin;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import java.util.concurrent.CompletableFuture;

public final class PixelProtectCommand {
    private static final int PAGE_SIZE = 50;
    private final Plugin plugin; private final Database database; private final RollbackService rollback; private final InspectService inspect; private final int maxHours,maxRadius,maxRecords;
    public PixelProtectCommand(Plugin plugin,Database database,RollbackService rollback,InspectService inspect,int maxHours,int maxRadius,int maxRecords){this.plugin=plugin;this.database=database;this.rollback=rollback;this.inspect=inspect;this.maxHours=maxHours;this.maxRadius=maxRadius;this.maxRecords=maxRecords;}
    public LiteralArgumentBuilder<CommandSourceStack> create(){return Commands.literal("pixelprotect").executes(c->version(c.getSource().getSender()))
        .then(Commands.literal("version").executes(c->version(c.getSource().getSender())))
        .then(Commands.literal("status").requires(s->s.getSender().hasPermission("pixelprotect.status")).executes(c->status(c.getSource().getSender())))
        .then(Commands.literal("inspect").requires(s->s.getSender().hasPermission("pixelprotect.inspect")).executes(c->inspect(c.getSource().getSender())))
        .then(Commands.literal("lookup").requires(s->s.getSender().hasPermission("pixelprotect.lookup")).then(Commands.argument("radius",IntegerArgumentType.integer(1,maxRadius)).then(Commands.argument("hours",IntegerArgumentType.integer(1,maxHours)).executes(c->lookup(c.getSource(),IntegerArgumentType.getInteger(c,"radius"),IntegerArgumentType.getInteger(c,"hours"),"")).then(Commands.argument("selectors",StringArgumentType.greedyString()).executes(c->lookup(c.getSource(),IntegerArgumentType.getInteger(c,"radius"),IntegerArgumentType.getInteger(c,"hours"),StringArgumentType.getString(c,"selectors")))))))
        .then(Commands.literal("near").requires(s->s.getSender().hasPermission("pixelprotect.lookup")).executes(c->lookup(c.getSource(),5,1,"")).then(Commands.argument("selectors",StringArgumentType.greedyString()).executes(c->lookup(c.getSource(),5,1,StringArgumentType.getString(c,"selectors")))))
        .then(Commands.literal("rollback").requires(s->s.getSender().hasPermission("pixelprotect.rollback")).then(Commands.literal("status").then(Commands.argument("job",StringArgumentType.word()).executes(c->rollbackStatus(c.getSource().getSender(),StringArgumentType.getString(c,"job")))).then(Commands.literal("cancel").then(Commands.argument("job",StringArgumentType.word()).executes(c->rollbackCancel(c.getSource().getSender(),StringArgumentType.getString(c,"job"))))).then(Commands.argument("radius",IntegerArgumentType.integer(1,maxRadius)).then(Commands.argument("hours",IntegerArgumentType.integer(1,maxHours)).executes(c->rollback(c.getSource(),IntegerArgumentType.getInteger(c,"radius"),IntegerArgumentType.getInteger(c,"hours"),"")).then(Commands.argument("selectors",StringArgumentType.greedyString()).executes(c->rollback(c.getSource(),IntegerArgumentType.getInteger(c,"radius"),IntegerArgumentType.getInteger(c,"hours"),StringArgumentType.getString(c,"selectors")))))))
        .then(Commands.literal("restore").requires(s->s.getSender().hasPermission("pixelprotect.rollback")).then(Commands.argument("job",StringArgumentType.word()).executes(c->restore(c.getSource().getSender(),StringArgumentType.getString(c,"job")))))
        .then(Commands.literal("purge").requires(s->s.getSender().hasPermission("pixelprotect.purge")).then(Commands.argument("days",IntegerArgumentType.integer(1,3650)).executes(c->purge(c.getSource().getSender(),IntegerArgumentType.getInteger(c,"days")))))
        .then(Commands.literal("help").executes(c->help(c.getSource().getSender())));}
    private int inspect(CommandSender s){if(!(s instanceof Player p))return message(s,"PixelProtect: inspect is only available to players.");boolean e=inspect.toggle(p);p.sendPlainMessage(e?"PixelProtect: inspect enabled. Click a block to inspect its history.":"PixelProtect: inspect disabled.");return Command.SINGLE_SUCCESS;}
    private int lookup(CommandSourceStack source,int defaultRadius,int defaultHours,String raw){final var parsed=SelectorParser.parse(tokens(raw),defaultRadius,defaultHours,maxRadius,maxHours);if(!parsed.errors().isEmpty())return sendErrors(source.getSender(),parsed.errors());final Location location=resolveLocation(source,parsed);if(location==null)return message(source.getSender(),"PixelProtect: no valid world/location context available.");final AuditQuery q=query(location,parsed);if(parsed.countOnly())database.count(q).thenAccept(n->send(source.getSender(),"PixelProtect: "+n+" matching audit record(s)."));else database.count(q).thenCombine(database.query(q),(count,entries)->new PageResult(count,entries,parsed.page())).thenAccept(r->sendLookup(source.getSender(),r)).exceptionally(t->{send(source.getSender(),"PixelProtect: query failed — "+rootMessage(t));return null;});source.getSender().sendPlainMessage("PixelProtect: querying audit history...");return Command.SINGLE_SUCCESS;}
    private int rollback(CommandSourceStack source,int defaultRadius,int defaultHours,String raw){final var parsed=SelectorParser.parse(tokens(raw),defaultRadius,defaultHours,maxRadius,maxHours);if(!parsed.errors().isEmpty())return sendErrors(source.getSender(),parsed.errors());final Location location=resolveLocation(source,parsed);if(location==null)return message(source.getSender(),"PixelProtect: no valid world/location context available.");final CommandSender sender=source.getSender();final AuditQuery q=query(location,parsed);if(parsed.countOnly()){database.count(q).thenAccept(n->send(sender,"PixelProtect: "+n+" matching audit record(s)."));return Command.SINGLE_SUCCESS;}database.query(new AuditQuery(q.world(),q.centerX(),q.centerY(),q.centerZ(),q.radius(),q.since(),q.until(),q.actorName(),q.includeActions(),q.excludeActions(),q.includeBlocks(),q.excludeBlocks(),maxRecords,0)).thenCompose(entries->{if(entries.isEmpty()){send(sender,parsed.preview()?"PixelProtect: preview found no matching records.":"PixelProtect: nothing to rollback.");return CompletableFuture.<String>completedFuture(null);}if(parsed.preview())return rollback.preview(entries).thenApply(r->"preview:"+r.applied()+":"+r.skipped());return rollback.start(entries).thenApply(j->"job:"+j.id());}).thenAccept(r->{if(r==null)return;if(r.startsWith("preview:")){String[]v=r.split(":");send(sender,"PixelProtect: preview complete. Would apply "+v[1]+", skip "+v[2]+".");}else send(sender,"PixelProtect: rollback job started: "+r.substring(4)+". Use /pixelprotect rollback status <job> for progress.");}).exceptionally(t->{send(sender,"PixelProtect: operation failed — "+rootMessage(t));return null;});return Command.SINGLE_SUCCESS;}
    private Location resolveLocation(CommandSourceStack source,SelectorParser.Parsed p){World w=p.world()==null?source.getLocation().getWorld():Bukkit.getWorld(p.world());if(w==null)return null;if(p.x()!=null)return new Location(w,p.x(),p.y(),p.z());if(p.chunkX()!=null)return new Location(w,p.chunkX()*16+8,source.getLocation().getBlockY(),p.chunkZ()*16+8);return source.getLocation();}
    private AuditQuery query(Location l,SelectorParser.Parsed p){long now=System.currentTimeMillis();int offset=(p.page()-1)*PAGE_SIZE;int x=l.getBlockX(),y=l.getBlockY(),z=l.getBlockZ();return new AuditQuery(l.getWorld().getUID(),x,y,z,p.radius(),now-p.hours()*3_600_000L,now,p.user(),p.includeActions(),p.excludeActions(),p.includeBlocks(),p.excludeBlocks(),Math.min(PAGE_SIZE,maxRecords),offset);}
    private int restore(CommandSender s,String raw){try{UUID id=UUID.fromString(raw);rollback.restore(id).thenAccept(r->send(s,"PixelProtect: restore complete. Applied "+r.applied()+", skipped "+r.skipped()+".")).exceptionally(t->{send(s,"PixelProtect: restore failed — "+rootMessage(t));return null;});return message(s,"PixelProtect: restore started...");}catch(IllegalArgumentException e){return message(s,"PixelProtect: invalid rollback job id.");}}
    private int rollbackStatus(CommandSender s,String raw){try{UUID id=UUID.fromString(raw);rollback.statusAsync(id).thenAccept(j->{if(j==null)send(s,"PixelProtect: rollback job not found.");else send(s,"PixelProtect: job "+j.id()+" — "+j.status()+" — processed "+j.processed()+"/"+j.total()+", applied "+j.applied()+", skipped "+j.skipped()+(j.error()==null?"":" — "+j.error()));});return message(s,"PixelProtect: loading rollback job status...");}catch(IllegalArgumentException e){return message(s,"PixelProtect: invalid rollback job id.");}}
    private int rollbackCancel(CommandSender s,String raw){try{UUID id=UUID.fromString(raw);rollback.cancelAsync(id).thenAccept(c->send(s,c?"PixelProtect: rollback cancellation requested.":"PixelProtect: rollback job not found or already finished."));return Command.SINGLE_SUCCESS;}catch(IllegalArgumentException e){return message(s,"PixelProtect: invalid rollback job id.");}}
    private int purge(CommandSender s,int days){database.purgeBefore(System.currentTimeMillis()-days*86_400_000L).thenAccept(n->send(s,"PixelProtect: purged "+n+" audit records."));s.sendPlainMessage("PixelProtect: purge started...");return Command.SINGLE_SUCCESS;}
    private int status(CommandSender s){database.count().thenAccept(n->send(s,"PixelProtect: operational. Schema "+database.schemaVersion()+", queue "+database.queueSize()+", stored audit records: "+n+"."));s.sendPlainMessage("PixelProtect: checking storage...");return Command.SINGLE_SUCCESS;}
    private int help(CommandSender s){s.sendPlainMessage("PixelProtect: /pixelprotect inspect");s.sendPlainMessage("PixelProtect: /pixelprotect lookup <radius> <hours> [u:player] [t:duration] [a:actions] [i:blocks] [e:blocks] [w:world] [c:x,y,z|ch:x,z] [#page:n] [#count]");s.sendPlainMessage("PixelProtect: /pixelprotect rollback <radius> <hours> [selectors] [#preview]");s.sendPlainMessage("PixelProtect: /pixelprotect rollback status <job>");s.sendPlainMessage("PixelProtect: /pixelprotect rollback cancel <job>");s.sendPlainMessage("PixelProtect: /pixelprotect restore <job>");return Command.SINGLE_SUCCESS;}
    private int version(CommandSender s){s.sendPlainMessage("PixelProtect 0.1.0 — standalone Paper 26.2 audit/rollback core");return Command.SINGLE_SUCCESS;}
    private void sendLookup(CommandSender s,PageResult r){long pages=Math.max(1,(r.total()+PAGE_SIZE-1)/PAGE_SIZE);send(s,"PixelProtect: page "+r.page()+"/"+pages+" — "+r.entries().size()+" record(s) of "+r.total()+".");r.entries().forEach(e->send(s,"#"+e.id()+" "+e.actorName()+" "+e.action()+" @ "+e.x()+","+e.y()+","+e.z()));if(r.page()<pages)send(s,"PixelProtect: next page: #page:"+(r.page()+1));}
    private static List<String>tokens(String raw){return raw==null||raw.isBlank()?List.of():Arrays.asList(raw.trim().split("\\s+"));}
    private int sendErrors(CommandSender s,List<String>e){e.forEach(x->s.sendPlainMessage("PixelProtect: "+x));return 0;}private int message(CommandSender s,String m){s.sendPlainMessage(m);return Command.SINGLE_SUCCESS;}private void send(CommandSender s,String m){Bukkit.getGlobalRegionScheduler().run(plugin,t->s.sendPlainMessage(m));}private static String rootMessage(Throwable t){Throwable c=t;while(c.getCause()!=null)c=c.getCause();return c.getMessage()==null?c.getClass().getSimpleName():c.getMessage();}
    private record PageResult(long total,List<AuditEntry>entries,int page){}
}
